# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontUserModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('telephone', models.CharField(default='18888888888', max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('_password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('avatar', models.URLField(blank=True)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('realname', models.CharField(max_length=20, null=True)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('gender', models.IntegerField(default=3)),
            ],
        ),
    ]
